#:kivy 1.10.0
#:import Factory kivy.factory.Factory

<CustomDropDown>:
    on_select:
        app.root.ids.Notes.ids.mainbutton.text = '{}'.format(args[1])
        app.root.Run_Draws_Test(args[1])


<Notes>:
    orientation: "vertical"

    FloatLayout:
        size_hint: None, None

        canvas.before:
            Color:
                rgba: 1, 1, 0, 1

        Button:
            id: mainbutton
            text: "Press to select"
            size_hint: None, None
            size: 150, 40
            on_release: Factory.CustomDropDown().open(self)

<MyScreenManager>:
    cols: 2
    BoxLayout:
        height: "45dp"
        size_hint_y: None
        Label:
            text: 'Selected serial port:'
            size_hint_x: 0.25
        Notes:
            id: Notes
            name: "Notes"
            size_hint_x: 1

   
