#:kivy 1.10.0
#:import Factory kivy.factory.Factory

<CustomDropDown>:
    on_select:
        app.root.ids.Notes.ids.mainbutton.text = '{}'.format(args[1])
        app.root.Run_Draws_Test(args[1])


<Notes>:
    orientation: "vertical"

    FloatLayout:
        size_hint: None, None

        canvas.before:
            Color:
                rgba: 1, 1, 0, 1

        Button:
            id: mainbutton
            text: "Menu name"
            font_size: 20
            size_hint: None, None
            size: 150, 50
            pos: 20,400
            on_release: Factory.CustomDropDown().open(self)

<MyScreenManager>:
    Notes:
        id:Notes
        name: 'Notes'